name: Mirror to Codeberg

on:
  push:
    branches: [ "main" ] # Kendi ana dal ismine göre (main/master) düzenle

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git remote add codeberg https://oauth2:${CODEBERG_TOKEN}@codeberg.org/universish/vanadium..mirror.git
          git push codeberg main --force
